//////////////////////////////////////////////////////////////////////////////////////////////
// File Name        :  driver.sv
// Description      :  It is the driver class which drives the DUT with the
// 		       transactions generated by the generator 
// Inputs           :  Nil
// Outputs          :  Nil
//////////////////////////////////////////////////////////////////////////////////////////////

class driver;
  // Virtual Interface and IPC decleration
  mailbox #(transaction) gen2drv;
  virtual deskew_inf vinf;
  int num_cases =120;
  // Parameterized constructor 
  function new(mailbox #(transaction) gen2drv, virtual deskew_inf vinf);
    this.gen2drv = gen2drv;
    this.vinf = vinf;
  endfunction
  // To reset the interface before starting
  task reset();
    vinf.drvinf.i_reset   <= 1;
    vinf.drvinf.i_stream1 <= 4'h0;
    vinf.drvinf.i_stream2 <= 4'h0;
    repeat(2) @(vinf.drvinf);
    vinf.drvinf.i_reset <= 0;
    @(vinf.drvinf);
    $display("[DRV] The interface is reseted done.");
  endtask
  // Task to transfer the packets for every clock
  task run();
    transaction rx;
    reset();
    repeat(num_cases) begin
      gen2drv.get(rx);
      vinf.drvinf.i_reset   <= rx.i_reset;  
      vinf.drvinf.i_stream1 <= rx.i_stream1;
      vinf.drvinf.i_stream2 <= rx.i_stream2;
	
      @(vinf.drvinf);
      rx.display("DRV");
    end
  endtask
endclass
